import { Plan, Tool } from './types';

export const DEFAULT_PLANS: Plan[] = [
  {
    id: 'free',
    name: 'Free',
    price: 0,
    period: 'month',
    dailyRequestLimit: 20,
    allowedModels: ['Gemini Flash', 'GPT-3.5 Turbo'],
    maxUploadMb: 5,
    features: [
      '20 AI requests / day',
      'Gemini Flash & GPT-3.5 models',
      'Basic AI Tools (Chat & Summarizer)',
      '5MB File Upload Limit',
      'Standard community support',
    ],
    description: 'Perfect for trying out AI tools and quick experiments.',
  },
  {
    id: 'starter',
    name: 'Starter',
    price: 19,
    period: 'month',
    dailyRequestLimit: 200,
    allowedModels: ['Gemini Flash', 'Gemini Pro', 'GPT-4 Turbo'],
    maxUploadMb: 25,
    features: [
      '200 AI requests / day',
      'GPT-4 & Gemini Pro access',
      'Code Generator & Email Writer access',
      '25MB File Upload Limit',
      'Developer API Key access (5,000 calls/mo)',
      'Fast response times',
    ],
    badge: 'Popular for Solo Devs',
    description: 'Ideal for freelance developers, writers, and small projects.',
    popular: true,
  },
  {
    id: 'pro',
    name: 'Pro',
    price: 49,
    period: 'month',
    dailyRequestLimit: 1500,
    allowedModels: ['GPT-4 Turbo', 'GPT-4o', 'Gemini 3.7 Flash', 'Claude 3.5 Sonnet', 'DALL-E 3 Prompt Engine'],
    maxUploadMb: 100,
    features: [
      'Unlimited daily requests (1,500/day soft cap)',
      'GPT-4o, Claude 3.5 & Image Generation tools',
      'Full Tool Suite (SQL, Image Prompt, Analysis)',
      '100MB File Upload Limit',
      'Unlimited API Key generation',
      'Priority server queue & zero latency throttling',
      'Export to Markdown, JSON & CSV',
    ],
    badge: 'Best Value',
    description: 'Designed for professionals, power creators, and scaling workflows.',
    priorityProcessing: true,
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    price: 199,
    period: 'month',
    dailyRequestLimit: 10000,
    allowedModels: ['All Models', 'GPT-4o', 'Claude 3.5 Sonnet', 'Gemini 3.7 Flash', 'Deep Research AI'],
    maxUploadMb: 500,
    features: [
      'Unlimited requests & custom rate limits',
      'Dedicated Team Access (up to 15 seats)',
      'Ultra Priority Processing (dedicated cluster)',
      '500MB File Upload Limit',
      '99.99% SLA & Dedicated Account Manager',
      'Custom AI Tool deployment & Webhook triggers',
      'Audit logs & SOC2-ready compliance export',
    ],
    badge: 'Enterprise Tier',
    description: 'Uncapped power for modern engineering and product teams.',
    priorityProcessing: true,
    teamSeats: 15,
  },
];

export const DEFAULT_TOOLS: Tool[] = [
  {
    id: 'ai-chat',
    name: 'AI Chat Assistant',
    description: 'Conversational intelligent companion for brainstorming, drafting, and problem solving.',
    category: 'chat',
    minPlan: 'free',
    systemPrompt: 'You are an ultra-capable, articulate, helpful AI SaaS assistant. Provide clear, structured, well-formatted responses.',
    iconName: 'MessageSquare',
    inputPlaceholder: 'Ask anything, discuss an architecture idea, or request an explanation...',
    samplePrompts: [
      'Explain the key differences between microservices and modular monoliths.',
      'How do distributed consensus algorithms like Raft work?',
      'Draft a comprehensive launch strategy for an AI SaaS startup.',
    ],
    enabled: true,
    availableModels: ['Gemini 3.7 Flash', 'GPT-4 Turbo', 'Claude 3.5 Sonnet'],
  },
  {
    id: 'ai-text-summarizer',
    name: 'AI Text Summarizer',
    description: 'Condense lengthy articles, papers, documents, and transcripts into crisp executive bullet points.',
    category: 'writing',
    minPlan: 'free',
    systemPrompt: 'You are an expert summarizer. Distill the given text into an executive summary, key takeaways, and action items.',
    iconName: 'FileText',
    inputPlaceholder: 'Paste long articles, documentation, meeting transcripts, or reports here...',
    samplePrompts: [
      'Summarize the quarterly financial report highlighting revenue growth and churn risk.',
      'Condense this 2,000 word blog post on React Server Components into 3 actionable bullets.',
      'Extract key deliverables and deadlines from these meeting notes.',
    ],
    enabled: true,
    availableModels: ['Gemini 3.7 Flash', 'GPT-3.5 Turbo', 'GPT-4 Turbo'],
  },
  {
    id: 'ai-code-generator',
    name: 'AI Code Generator & Refactor',
    description: 'Generate production-ready code, unit tests, bug fixes, and API integrations in any language.',
    category: 'coding',
    minPlan: 'starter',
    systemPrompt: 'You are a staff principal software engineer. Generate clean, safe, well-commented, production-grade code with TypeScript types and best practices.',
    iconName: 'Code2',
    inputPlaceholder: 'Describe the feature, bug, or algorithm you need code for (e.g., "Next.js 15 JWT auth middleware")...',
    samplePrompts: [
      'Write a rate-limiter middleware for Next.js App Router using Redis sliding window.',
      'Create a React hook for debounced async search with automatic cancellation.',
      'Write a Python script to parse CSV files and stream upload rows to PostgreSQL.',
    ],
    enabled: true,
    availableModels: ['Gemini 3.7 Flash', 'GPT-4 Turbo', 'Claude 3.5 Sonnet'],
  },
  {
    id: 'ai-email-writer',
    name: 'AI Email & Copy Writer',
    description: 'Craft high-converting cold outreach, product updates, investor newsletters, and customer support replies.',
    category: 'writing',
    minPlan: 'starter',
    systemPrompt: 'You are a world-class copywriter and communications director. Write compelling, concise, high-converting emails.',
    iconName: 'Mail',
    inputPlaceholder: 'What email do you need? (e.g., "Follow up email after a SaaS product demo, addressing budget concerns")...',
    samplePrompts: [
      'Write a polite but firm follow-up email to an overdue enterprise invoice.',
      'Draft a celebratory product launch announcement for version 2.0 with a 20% discount offer.',
      'Write a warm onboarding email introducing premium features to a newly subscribed customer.',
    ],
    enabled: true,
    availableModels: ['Gemini 3.7 Flash', 'GPT-4 Turbo', 'GPT-3.5 Turbo'],
  },
  {
    id: 'ai-image-prompt',
    name: 'AI Image Prompt Generator',
    description: 'Engineer hyper-detailed, photorealistic prompts for Midjourney, Stable Diffusion, and DALL-E 3.',
    category: 'image',
    minPlan: 'pro',
    systemPrompt: 'You are an award-winning prompt engineer and art director. Generate structured, photorealistic, atmospheric prompts with lighting, lens, and rendering parameters.',
    iconName: 'Sparkles',
    inputPlaceholder: 'Describe your visual concept (e.g., "Futuristic cyberpunk Tokyo alleyway in the rain")...',
    samplePrompts: [
      'Isometric 3D render of a cozy modern developer workspace with glowing neon flora.',
      'Cinematic editorial portrait of a cybernetic architect in natural golden hour lighting, 85mm f/1.4.',
      'Minimalist Bauhaus vector poster promoting a fictional space exploration summit.',
    ],
    enabled: true,
    availableModels: ['Gemini 3.7 Flash', 'GPT-4o', 'DALL-E 3 Prompt Engine'],
  },
  {
    id: 'ai-sql-builder',
    name: 'AI SQL & Query Generator',
    description: 'Convert plain English questions into optimized SQL queries, indexes, and schema migrations.',
    category: 'coding',
    minPlan: 'pro',
    systemPrompt: 'You are an elite database administrator. Convert requirements into optimized SQL queries with indexes and explanations.',
    iconName: 'Database',
    inputPlaceholder: 'Ask for a query (e.g., "Find monthly active users who made more than 3 purchases in the last 90 days")...',
    samplePrompts: [
      'Write a query to calculate customer churn rate month-over-month in PostgreSQL.',
      'Generate a query to find top 5 products by revenue for each category with window functions.',
      'Create a database migration adding an audit_logs table with JSONB metadata and indexing.',
    ],
    enabled: true,
    availableModels: ['Gemini 3.7 Flash', 'GPT-4o', 'Claude 3.5 Sonnet'],
  },
];
